### ISSUE TITLE
A couple of changes

### ISSUE THREAD

**Issue by Sxtanna** [ServerCore/ServerCore#11]
- [X] Liskov Substitution Principle
[ModuleLoader.java#L45](https://github.com/ServerCore/ServerCore/blob/master/src/main/java/me/kingtux/servercore/universal/api/moduleloader/ModuleLoader.java#L45)

- [x] This method could use a stream and forEach to iterate over each entry instead of calling Map#get
[ModuleLoader.java#L57](https://github.com/ServerCore/ServerCore/blob/master/src/main/java/me/kingtux/servercore/universal/api/moduleloader/ModuleLoader.java#L57)

- [X] Naming conventions?
[ModuleLoader.java#L105](https://github.com/ServerCore/ServerCore/blob/master/src/main/java/me/kingtux/servercore/universal/api/moduleloader/ModuleLoader.java#L105)

- [x] Use either FileFilter or FilenameFilter to gather needed files, you can even use a stream to collect the results
[ModuleLoader.java#L106](https://github.com/ServerCore/ServerCore/blob/master/src/main/java/me/kingtux/servercore/universal/api/moduleloader/ModuleLoader.java#L106)

- [X] This class should be final
[SpigotMain.java#L49](https://github.com/ServerCore/ServerCore/blob/master/src/main/java/net/nickac/servercore/spigot/SpigotMain.java#L49)

- [X] This does nothing
[SpigotMain.java#L51](https://github.com/ServerCore/ServerCore/blob/master/src/main/java/net/nickac/servercore/spigot/SpigotMain.java#L51)

Any particular reason you actually need this? 
[SpigotMain.java#L59](https://github.com/ServerCore/ServerCore/blob/master/src/main/java/net/nickac/servercore/spigot/SpigotMain.java#L59)

(Edited by NickAc to turn this issue into a task list that needs to be addressed)

**Comment by wherkamp** [comment]
If you would like to help. hit that fork button and fix it. :smile:

**Comment by NickAcPT** [comment]
Reopening because there are still stuff to fix.

**Comment by NickAcPT** [comment]
@Sxtanna Thank you for your help. Even if indirectly, your help was great.

Hope to see you help us in the future.
