### ISSUE TITLE
Migrate to Maven

### ISSUE THREAD

**Issue by NickAcPT** [ServerCore/ServerCore#4]

**Comment by wherkamp** [comment]
Since I have no idea what you want I am closing this.

**Comment by NickAcPT** [comment]
You said you would add Maven to get the dependencies.
I created this issue to make track of what's isn't done.

**Comment by wherkamp** [comment]
I have not started working on the Maven yet. I will get on that tonight.

**Comment by wherkamp** [comment]
Could you give me links to the libraries I will be needing. Excluding BungeeCord and Spigot

**Comment by NickAcPT** [comment]
Lombok - https://projectlombok.org/mavenrepo/

HikariCP - https://brettwooldridge.github.io/HikariCP/
(Needs to be shaded into the plugin)

If possible, please make it so it also uses file in a folder called 'libs'

Thank you so much.

**Comment by wherkamp** [comment]
I will try. Weirdly the Maven keeps throwing a error. It looks like it failing to find something.

**Comment by NickAcPT** [comment]
Try to remove one at a time. That way you'll see what's working and what's
not.




*Obrigado,*

*André Cardoso*

*(PS: Esta Assinatura É Automática!)*

**Comment by wherkamp** [comment]
Could you give it a look over?
https://github.com/wherkamp/ServerCore/blob/master/pom.xml

**Comment by NickAcPT** [comment]
I think I'm not in the position to help you with this. Sorry, but I never
tried to use Maven.
You should go to the spigot forum.




*Obrigado,*

*André Cardoso*

*(PS: Esta Assinatura É Automática!)*

**Comment by wherkamp** [comment]
I have only used a few times and it only been with Spigot Alone.

**Comment by wherkamp** [comment]
I will go ask.

**Comment by NickAcPT** [comment]
I tested maven and HikariCP is not shaded into the final jar.

**Comment by wherkamp** [comment]
May I ask what do you mean?

**Comment by wherkamp** [comment]
Sorry What is the definition of Shaded in this scenario?

**Comment by NickAcPT** [comment]
Sorry for not being explicit. Shading in maven is when a dependency gets copied to the final jar.
Found [this](https://www.spigotmc.org/threads/how-to-shade-in-maven.102703/) thread on spigot.
Sorry again for bothering you with this kind of stuff.

**Comment by wherkamp** [comment]
Ok, add inside the jar the HikariCP jar?

**Comment by NickAcPT** [comment]
Yes, that's what Maven shade does automatically.

**Comment by NickAcPT** [comment]
No, Maven shade copies the dependencies jar's content inside our final jar.

**Comment by wherkamp** [comment]
Ok I will set that up later.

**Comment by wherkamp** [comment]
I have Implemented Shading.

**Comment by wherkamp** [comment]
I would like to note that Hibernate has been added :+1:
