### ISSUE TITLE
Implement Module Loader

### ISSUE THREAD

**Issue by NickAcPT** [ServerCore/ServerCore#5]

**Comment by wherkamp** [comment]
This needs to be tested and implemented into the rest of the plugin.

**Comment by NickAcPT** [comment]
@wherkamp Don't worry because this will be tested.
The plugin will then revolve around the Modular design.

**Comment by wherkamp** [comment]
I was just stating that the code is ready to be test in the section.
I have implamented into the onEnable();
I do need to add onDisable() next.

**Comment by wherkamp** [comment]
This has been decided not to happen. :+1: [[selfie-0 uploading...]]
